source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'QRCoderOSXExample', :exclusive => true do
    platform :osx, '10.9'
    pod "QRCoder", :path => "../"
end

target 'QRCoderOSXTests', :exclusive => true do
    platform :osx, '10.9'
    pod "QRCoder", :path => "../"
end

target 'QRCoderiOSExample', :exclusive => true do
    platform :ios, '8.0'
    pod "QRCoder", :path => "../"
end

target 'QRCoderiOSTests', :exclusive => true do
    platform :ios, '8.0'
    pod "QRCoder", :path => "../"
end
