source 'https://github.com/CocoaPods/Specs.git'

target 'QRCoder', :exclusive => true do
  pod "QRCoder", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "QRCoder", :path => "../"

  pod 'FBSnapshotTestCase'
end
