source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'QRCoderExampleOSX', :exclusive => true do
    platform :osx, '10.9'
    pod "QRCoder", :path => "../"
end

target 'QRCoderOSXTests', :exclusive => true do
    platform :osx, '10.9'
    pod "QRCoder", :path => "../"
end
